/**
 * Países e respectivos gentílicos, em português.
 *
 * Lista estática e versionada de propósito: não há API pública fiável para
 * gentílicos em português, e uma chamada externa no meio do cadastro só
 * acrescentaria latência e um ponto de falha.
 *
 * Os nomes foram gerados com Intl.DisplayNames('pt'); os gentílicos são curados
 * à mão. Códigos ISO 3166-1 alpha-2.
 */

export interface Pais {
    /** Código ISO 3166-1 alpha-2, ex.: "AO" */
    codigo: string;
    /** Nome em português, ex.: "Angola" */
    nome: string;
    /** Gentílico em português, ex.: "Angolana" */
    nacionalidade: string;
}

export const PAISES: Pais[] = [
    { codigo: 'AD', nome: 'Andorra', nacionalidade: 'Andorrana' },
    { codigo: 'AE', nome: 'Emirados Árabes Unidos', nacionalidade: 'Emiradense' },
    { codigo: 'AF', nome: 'Afeganistão', nacionalidade: 'Afegã' },
    { codigo: 'AG', nome: 'Antígua e Barbuda', nacionalidade: 'Antiguana' },
    { codigo: 'AI', nome: 'Anguila', nacionalidade: 'Anguilana' },
    { codigo: 'AL', nome: 'Albânia', nacionalidade: 'Albanesa' },
    { codigo: 'AM', nome: 'Armênia', nacionalidade: 'Arménia' },
    { codigo: 'AO', nome: 'Angola', nacionalidade: 'Angolana' },
    { codigo: 'AR', nome: 'Argentina', nacionalidade: 'Argentina' },
    { codigo: 'AS', nome: 'Samoa Americana', nacionalidade: 'Samoana' },
    { codigo: 'AT', nome: 'Áustria', nacionalidade: 'Austríaca' },
    { codigo: 'AU', nome: 'Austrália', nacionalidade: 'Australiana' },
    { codigo: 'AW', nome: 'Aruba', nacionalidade: 'Arubana' },
    { codigo: 'AX', nome: 'Ilhas Aland', nacionalidade: 'Alandesa' },
    { codigo: 'AZ', nome: 'Azerbaijão', nacionalidade: 'Azerbaijana' },
    { codigo: 'BA', nome: 'Bósnia e Herzegovina', nacionalidade: 'Bósnia' },
    { codigo: 'BB', nome: 'Barbados', nacionalidade: 'Barbadiana' },
    { codigo: 'BD', nome: 'Bangladesh', nacionalidade: 'Bangladeshiana' },
    { codigo: 'BE', nome: 'Bélgica', nacionalidade: 'Belga' },
    { codigo: 'BF', nome: 'Burquina Faso', nacionalidade: 'Burquinense' },
    { codigo: 'BG', nome: 'Bulgária', nacionalidade: 'Búlgara' },
    { codigo: 'BH', nome: 'Barein', nacionalidade: 'Bareinita' },
    { codigo: 'BI', nome: 'Burundi', nacionalidade: 'Burundiana' },
    { codigo: 'BJ', nome: 'Benin', nacionalidade: 'Beninense' },
    { codigo: 'BL', nome: 'São Bartolomeu', nacionalidade: 'São-bartolomeense' },
    { codigo: 'BM', nome: 'Bermudas', nacionalidade: 'Bermudense' },
    { codigo: 'BN', nome: 'Brunei', nacionalidade: 'Bruneana' },
    { codigo: 'BO', nome: 'Bolívia', nacionalidade: 'Boliviana' },
    { codigo: 'BQ', nome: 'Países Baixos Caribenhos', nacionalidade: 'Neerlandesa' },
    { codigo: 'BR', nome: 'Brasil', nacionalidade: 'Brasileira' },
    { codigo: 'BS', nome: 'Bahamas', nacionalidade: 'Bahamense' },
    { codigo: 'BT', nome: 'Butão', nacionalidade: 'Butanesa' },
    { codigo: 'BW', nome: 'Botsuana', nacionalidade: 'Botsuanesa' },
    { codigo: 'BY', nome: 'Bielorrússia', nacionalidade: 'Bielorrussa' },
    { codigo: 'BZ', nome: 'Belize', nacionalidade: 'Belizenha' },
    { codigo: 'CA', nome: 'Canadá', nacionalidade: 'Canadiana' },
    { codigo: 'CD', nome: 'República Democrática do Congo', nacionalidade: 'Congolesa' },
    { codigo: 'CF', nome: 'República Centro-Africana', nacionalidade: 'Centro-africana' },
    { codigo: 'CG', nome: 'República do Congo', nacionalidade: 'Congolesa' },
    { codigo: 'CH', nome: 'Suíça', nacionalidade: 'Suíça' },
    { codigo: 'CI', nome: 'Costa do Marfim', nacionalidade: 'Marfinense' },
    { codigo: 'CK', nome: 'Ilhas Cook', nacionalidade: 'Cookiana' },
    { codigo: 'CL', nome: 'Chile', nacionalidade: 'Chilena' },
    { codigo: 'CM', nome: 'Camarões', nacionalidade: 'Camaronesa' },
    { codigo: 'CN', nome: 'China', nacionalidade: 'Chinesa' },
    { codigo: 'CO', nome: 'Colômbia', nacionalidade: 'Colombiana' },
    { codigo: 'CR', nome: 'Costa Rica', nacionalidade: 'Costa-riquenha' },
    { codigo: 'CU', nome: 'Cuba', nacionalidade: 'Cubana' },
    { codigo: 'CV', nome: 'Cabo Verde', nacionalidade: 'Cabo-verdiana' },
    { codigo: 'CW', nome: 'Curaçao', nacionalidade: 'Curaçauense' },
    { codigo: 'CY', nome: 'Chipre', nacionalidade: 'Cipriota' },
    { codigo: 'CZ', nome: 'Tchéquia', nacionalidade: 'Checa' },
    { codigo: 'DE', nome: 'Alemanha', nacionalidade: 'Alemã' },
    { codigo: 'DJ', nome: 'Djibuti', nacionalidade: 'Djibutiense' },
    { codigo: 'DK', nome: 'Dinamarca', nacionalidade: 'Dinamarquesa' },
    { codigo: 'DM', nome: 'Dominica', nacionalidade: 'Dominiquense' },
    { codigo: 'DO', nome: 'República Dominicana', nacionalidade: 'Dominicana' },
    { codigo: 'DZ', nome: 'Argélia', nacionalidade: 'Argelina' },
    { codigo: 'EC', nome: 'Equador', nacionalidade: 'Equatoriana' },
    { codigo: 'EE', nome: 'Estônia', nacionalidade: 'Estónia' },
    { codigo: 'EG', nome: 'Egito', nacionalidade: 'Egípcia' },
    { codigo: 'EH', nome: 'Saara Ocidental', nacionalidade: 'Sarauí' },
    { codigo: 'ER', nome: 'Eritreia', nacionalidade: 'Eritreia' },
    { codigo: 'ES', nome: 'Espanha', nacionalidade: 'Espanhola' },
    { codigo: 'ET', nome: 'Etiópia', nacionalidade: 'Etíope' },
    { codigo: 'FI', nome: 'Finlândia', nacionalidade: 'Finlandesa' },
    { codigo: 'FJ', nome: 'Fiji', nacionalidade: 'Fijiana' },
    { codigo: 'FK', nome: 'Ilhas Malvinas', nacionalidade: 'Malvinense' },
    { codigo: 'FM', nome: 'Micronésia', nacionalidade: 'Micronésia' },
    { codigo: 'FO', nome: 'Ilhas Faroé', nacionalidade: 'Faroesa' },
    { codigo: 'FR', nome: 'França', nacionalidade: 'Francesa' },
    { codigo: 'GA', nome: 'Gabão', nacionalidade: 'Gabonesa' },
    { codigo: 'GB', nome: 'Reino Unido', nacionalidade: 'Britânica' },
    { codigo: 'GD', nome: 'Granada', nacionalidade: 'Granadina' },
    { codigo: 'GE', nome: 'Geórgia', nacionalidade: 'Georgiana' },
    { codigo: 'GF', nome: 'Guiana Francesa', nacionalidade: 'Guianense' },
    { codigo: 'GG', nome: 'Guernsey', nacionalidade: 'Guernesiana' },
    { codigo: 'GH', nome: 'Gana', nacionalidade: 'Ganesa' },
    { codigo: 'GI', nome: 'Gibraltar', nacionalidade: 'Gibraltina' },
    { codigo: 'GL', nome: 'Groenlândia', nacionalidade: 'Gronelandesa' },
    { codigo: 'GM', nome: 'Gâmbia', nacionalidade: 'Gambiana' },
    { codigo: 'GN', nome: 'Guiné', nacionalidade: 'Guineense' },
    { codigo: 'GP', nome: 'Guadalupe', nacionalidade: 'Guadalupense' },
    { codigo: 'GQ', nome: 'Guiné Equatorial', nacionalidade: 'Equato-guineense' },
    { codigo: 'GR', nome: 'Grécia', nacionalidade: 'Grega' },
    { codigo: 'GT', nome: 'Guatemala', nacionalidade: 'Guatemalteca' },
    { codigo: 'GU', nome: 'Guam', nacionalidade: 'Guamesa' },
    { codigo: 'GW', nome: 'Guiné-Bissau', nacionalidade: 'Guineense' },
    { codigo: 'GY', nome: 'Guiana', nacionalidade: 'Guianesa' },
    { codigo: 'HK', nome: 'Hong Kong, RAE da China', nacionalidade: 'Hong-konguesa' },
    { codigo: 'HN', nome: 'Honduras', nacionalidade: 'Hondurenha' },
    { codigo: 'HR', nome: 'Croácia', nacionalidade: 'Croata' },
    { codigo: 'HT', nome: 'Haiti', nacionalidade: 'Haitiana' },
    { codigo: 'HU', nome: 'Hungria', nacionalidade: 'Húngara' },
    { codigo: 'ID', nome: 'Indonésia', nacionalidade: 'Indonésia' },
    { codigo: 'IE', nome: 'Irlanda', nacionalidade: 'Irlandesa' },
    { codigo: 'IL', nome: 'Israel', nacionalidade: 'Israelita' },
    { codigo: 'IM', nome: 'Ilha de Man', nacionalidade: 'Manesa' },
    { codigo: 'IN', nome: 'Índia', nacionalidade: 'Indiana' },
    { codigo: 'IQ', nome: 'Iraque', nacionalidade: 'Iraquiana' },
    { codigo: 'IR', nome: 'Irã', nacionalidade: 'Iraniana' },
    { codigo: 'IS', nome: 'Islândia', nacionalidade: 'Islandesa' },
    { codigo: 'IT', nome: 'Itália', nacionalidade: 'Italiana' },
    { codigo: 'JE', nome: 'Jersey', nacionalidade: 'Jersiana' },
    { codigo: 'JM', nome: 'Jamaica', nacionalidade: 'Jamaicana' },
    { codigo: 'JO', nome: 'Jordânia', nacionalidade: 'Jordana' },
    { codigo: 'JP', nome: 'Japão', nacionalidade: 'Japonesa' },
    { codigo: 'KE', nome: 'Quênia', nacionalidade: 'Queniana' },
    { codigo: 'KG', nome: 'Quirguistão', nacionalidade: 'Quirguiz' },
    { codigo: 'KH', nome: 'Camboja', nacionalidade: 'Cambojana' },
    { codigo: 'KI', nome: 'Quiribati', nacionalidade: 'Quiribatiana' },
    { codigo: 'KM', nome: 'Comores', nacionalidade: 'Comorense' },
    { codigo: 'KN', nome: 'São Cristóvão e Névis', nacionalidade: 'São-cristovense' },
    { codigo: 'KP', nome: 'Coreia do Norte', nacionalidade: 'Norte-coreana' },
    { codigo: 'KR', nome: 'Coreia do Sul', nacionalidade: 'Sul-coreana' },
    { codigo: 'KW', nome: 'Kuwait', nacionalidade: 'Kuwaitiana' },
    { codigo: 'KY', nome: 'Ilhas Cayman', nacionalidade: 'Caimanesa' },
    { codigo: 'KZ', nome: 'Cazaquistão', nacionalidade: 'Cazaque' },
    { codigo: 'LA', nome: 'Laos', nacionalidade: 'Laociana' },
    { codigo: 'LB', nome: 'Líbano', nacionalidade: 'Libanesa' },
    { codigo: 'LC', nome: 'Santa Lúcia', nacionalidade: 'Santa-lucense' },
    { codigo: 'LI', nome: 'Liechtenstein', nacionalidade: 'Listenstainiana' },
    { codigo: 'LK', nome: 'Sri Lanka', nacionalidade: 'Cingalesa' },
    { codigo: 'LR', nome: 'Libéria', nacionalidade: 'Liberiana' },
    { codigo: 'LS', nome: 'Lesoto', nacionalidade: 'Lesotiana' },
    { codigo: 'LT', nome: 'Lituânia', nacionalidade: 'Lituana' },
    { codigo: 'LU', nome: 'Luxemburgo', nacionalidade: 'Luxemburguesa' },
    { codigo: 'LV', nome: 'Letônia', nacionalidade: 'Letã' },
    { codigo: 'LY', nome: 'Líbia', nacionalidade: 'Líbia' },
    { codigo: 'MA', nome: 'Marrocos', nacionalidade: 'Marroquina' },
    { codigo: 'MC', nome: 'Mônaco', nacionalidade: 'Monegasca' },
    { codigo: 'MD', nome: 'Moldávia', nacionalidade: 'Moldava' },
    { codigo: 'ME', nome: 'Montenegro', nacionalidade: 'Montenegrina' },
    { codigo: 'MF', nome: 'São Martinho', nacionalidade: 'São-martinhense' },
    { codigo: 'MG', nome: 'Madagascar', nacionalidade: 'Malgaxe' },
    { codigo: 'MH', nome: 'Ilhas Marshall', nacionalidade: 'Marshallina' },
    { codigo: 'MK', nome: 'Macedônia do Norte', nacionalidade: 'Macedónia' },
    { codigo: 'ML', nome: 'Mali', nacionalidade: 'Maliana' },
    { codigo: 'MM', nome: 'Mianmar (Birmânia)', nacionalidade: 'Birmanesa' },
    { codigo: 'MN', nome: 'Mongólia', nacionalidade: 'Mongol' },
    { codigo: 'MO', nome: 'Macau, RAE da China', nacionalidade: 'Macaense' },
    { codigo: 'MP', nome: 'Ilhas Marianas do Norte', nacionalidade: 'Mariana' },
    { codigo: 'MQ', nome: 'Martinica', nacionalidade: 'Martinicana' },
    { codigo: 'MR', nome: 'Mauritânia', nacionalidade: 'Mauritana' },
    { codigo: 'MS', nome: 'Montserrat', nacionalidade: 'Monserratense' },
    { codigo: 'MT', nome: 'Malta', nacionalidade: 'Maltesa' },
    { codigo: 'MU', nome: 'Maurício', nacionalidade: 'Mauriciana' },
    { codigo: 'MV', nome: 'Maldivas', nacionalidade: 'Maldiva' },
    { codigo: 'MW', nome: 'Malaui', nacionalidade: 'Malauiana' },
    { codigo: 'MX', nome: 'México', nacionalidade: 'Mexicana' },
    { codigo: 'MY', nome: 'Malásia', nacionalidade: 'Malaia' },
    { codigo: 'MZ', nome: 'Moçambique', nacionalidade: 'Moçambicana' },
    { codigo: 'NA', nome: 'Namíbia', nacionalidade: 'Namibiana' },
    { codigo: 'NC', nome: 'Nova Caledônia', nacionalidade: 'Neocaledónia' },
    { codigo: 'NE', nome: 'Níger', nacionalidade: 'Nigerina' },
    { codigo: 'NF', nome: 'Ilha Norfolk', nacionalidade: 'Norfolquina' },
    { codigo: 'NG', nome: 'Nigéria', nacionalidade: 'Nigeriana' },
    { codigo: 'NI', nome: 'Nicarágua', nacionalidade: 'Nicaraguense' },
    { codigo: 'NL', nome: 'Países Baixos', nacionalidade: 'Neerlandesa' },
    { codigo: 'NO', nome: 'Noruega', nacionalidade: 'Norueguesa' },
    { codigo: 'NP', nome: 'Nepal', nacionalidade: 'Nepalesa' },
    { codigo: 'NR', nome: 'Nauru', nacionalidade: 'Nauruana' },
    { codigo: 'NU', nome: 'Niue', nacionalidade: 'Niuana' },
    { codigo: 'NZ', nome: 'Nova Zelândia', nacionalidade: 'Neozelandesa' },
    { codigo: 'OM', nome: 'Omã', nacionalidade: 'Omanense' },
    { codigo: 'PA', nome: 'Panamá', nacionalidade: 'Panamiana' },
    { codigo: 'PE', nome: 'Peru', nacionalidade: 'Peruana' },
    { codigo: 'PF', nome: 'Polinésia Francesa', nacionalidade: 'Polinésia' },
    { codigo: 'PG', nome: 'Papua-Nova Guiné', nacionalidade: 'Papuásia' },
    { codigo: 'PH', nome: 'Filipinas', nacionalidade: 'Filipina' },
    { codigo: 'PK', nome: 'Paquistão', nacionalidade: 'Paquistanesa' },
    { codigo: 'PL', nome: 'Polônia', nacionalidade: 'Polaca' },
    { codigo: 'PM', nome: 'São Pedro e Miquelão', nacionalidade: 'São-pedrense' },
    { codigo: 'PR', nome: 'Porto Rico', nacionalidade: 'Porto-riquenha' },
    { codigo: 'PS', nome: 'Territórios palestinos', nacionalidade: 'Palestiniana' },
    { codigo: 'PT', nome: 'Portugal', nacionalidade: 'Portuguesa' },
    { codigo: 'PW', nome: 'Palau', nacionalidade: 'Palauana' },
    { codigo: 'PY', nome: 'Paraguai', nacionalidade: 'Paraguaia' },
    { codigo: 'QA', nome: 'Catar', nacionalidade: 'Catarense' },
    { codigo: 'RE', nome: 'Reunião', nacionalidade: 'Reunionense' },
    { codigo: 'RO', nome: 'Romênia', nacionalidade: 'Romena' },
    { codigo: 'RS', nome: 'Sérvia', nacionalidade: 'Sérvia' },
    { codigo: 'RU', nome: 'Rússia', nacionalidade: 'Russa' },
    { codigo: 'RW', nome: 'Ruanda', nacionalidade: 'Ruandesa' },
    { codigo: 'SA', nome: 'Arábia Saudita', nacionalidade: 'Saudita' },
    { codigo: 'SB', nome: 'Ilhas Salomão', nacionalidade: 'Salomónica' },
    { codigo: 'SC', nome: 'Seicheles', nacionalidade: 'Seichelense' },
    { codigo: 'SD', nome: 'Sudão', nacionalidade: 'Sudanesa' },
    { codigo: 'SE', nome: 'Suécia', nacionalidade: 'Sueca' },
    { codigo: 'SG', nome: 'Singapura', nacionalidade: 'Singapurense' },
    { codigo: 'SH', nome: 'Santa Helena', nacionalidade: 'Santa-helenense' },
    { codigo: 'SI', nome: 'Eslovênia', nacionalidade: 'Eslovena' },
    { codigo: 'SK', nome: 'Eslováquia', nacionalidade: 'Eslovaca' },
    { codigo: 'SL', nome: 'Serra Leoa', nacionalidade: 'Serra-leonesa' },
    { codigo: 'SM', nome: 'San Marino', nacionalidade: 'Samarinesa' },
    { codigo: 'SN', nome: 'Senegal', nacionalidade: 'Senegalesa' },
    { codigo: 'SO', nome: 'Somália', nacionalidade: 'Somali' },
    { codigo: 'SR', nome: 'Suriname', nacionalidade: 'Surinamesa' },
    { codigo: 'SS', nome: 'Sudão do Sul', nacionalidade: 'Sul-sudanesa' },
    { codigo: 'ST', nome: 'São Tomé e Príncipe', nacionalidade: 'São-tomense' },
    { codigo: 'SV', nome: 'El Salvador', nacionalidade: 'Salvadorenha' },
    { codigo: 'SX', nome: 'Sint Maarten', nacionalidade: 'São-martinhense' },
    { codigo: 'SY', nome: 'Síria', nacionalidade: 'Síria' },
    { codigo: 'SZ', nome: 'Essuatíni', nacionalidade: 'Suázi' },
    { codigo: 'TC', nome: 'Ilhas Turcas e Caicos', nacionalidade: 'Turquesa' },
    { codigo: 'TD', nome: 'Chade', nacionalidade: 'Chadiana' },
    { codigo: 'TG', nome: 'Togo', nacionalidade: 'Togolesa' },
    { codigo: 'TH', nome: 'Tailândia', nacionalidade: 'Tailandesa' },
    { codigo: 'TJ', nome: 'Tadjiquistão', nacionalidade: 'Tajique' },
    { codigo: 'TK', nome: 'Tokelau', nacionalidade: 'Toquelauana' },
    { codigo: 'TL', nome: 'Timor-Leste', nacionalidade: 'Timorense' },
    { codigo: 'TM', nome: 'Turcomenistão', nacionalidade: 'Turcomena' },
    { codigo: 'TN', nome: 'Tunísia', nacionalidade: 'Tunisina' },
    { codigo: 'TO', nome: 'Tonga', nacionalidade: 'Tonganesa' },
    { codigo: 'TR', nome: 'Turquia', nacionalidade: 'Turca' },
    { codigo: 'TT', nome: 'Trinidad e Tobago', nacionalidade: 'Trinitária' },
    { codigo: 'TV', nome: 'Tuvalu', nacionalidade: 'Tuvaluana' },
    { codigo: 'TW', nome: 'Taiwan', nacionalidade: 'Taiwanesa' },
    { codigo: 'TZ', nome: 'Tanzânia', nacionalidade: 'Tanzaniana' },
    { codigo: 'UA', nome: 'Ucrânia', nacionalidade: 'Ucraniana' },
    { codigo: 'UG', nome: 'Uganda', nacionalidade: 'Ugandesa' },
    { codigo: 'US', nome: 'Estados Unidos', nacionalidade: 'Norte-americana' },
    { codigo: 'UY', nome: 'Uruguai', nacionalidade: 'Uruguaia' },
    { codigo: 'UZ', nome: 'Uzbequistão', nacionalidade: 'Usbeque' },
    { codigo: 'VA', nome: 'Cidade do Vaticano', nacionalidade: 'Vaticana' },
    { codigo: 'VC', nome: 'São Vicente e Granadinas', nacionalidade: 'São-vicentina' },
    { codigo: 'VE', nome: 'Venezuela', nacionalidade: 'Venezuelana' },
    { codigo: 'VG', nome: 'Ilhas Virgens Britânicas', nacionalidade: 'Virgemense' },
    { codigo: 'VI', nome: 'Ilhas Virgens Americanas', nacionalidade: 'Virgemense' },
    { codigo: 'VN', nome: 'Vietnã', nacionalidade: 'Vietnamita' },
    { codigo: 'VU', nome: 'Vanuatu', nacionalidade: 'Vanuatuense' },
    { codigo: 'WF', nome: 'Wallis e Futuna', nacionalidade: 'Wallisiana' },
    { codigo: 'WS', nome: 'Samoa', nacionalidade: 'Samoana' },
    { codigo: 'YE', nome: 'Iêmen', nacionalidade: 'Iemenita' },
    { codigo: 'YT', nome: 'Mayotte', nacionalidade: 'Maiotense' },
    { codigo: 'ZA', nome: 'África do Sul', nacionalidade: 'Sul-africana' },
    { codigo: 'ZM', nome: 'Zâmbia', nacionalidade: 'Zambiana' },
    { codigo: 'ZW', nome: 'Zimbábue', nacionalidade: 'Zimbabuense' },
].sort((a, b) => a.nome.localeCompare(b.nome, 'pt'));

/** Procura um país pelo código ISO. */
export const paisPorCodigo = (codigo?: string): Pais | undefined =>
    codigo ? PAISES.find((p) => p.codigo === codigo.toUpperCase()) : undefined;

/** Gentílico correspondente ao país, ou string vazia se desconhecido. */
export const nacionalidadeDoPais = (codigo?: string): string =>
    paisPorCodigo(codigo)?.nacionalidade || '';
